### ISSUE TITLE
MODEL_PATH = 'models/your_model.h5' gives error

### ISSUE THREAD

**Issue by Afshan-anwar** [mtobeiyf/keras-flask-deploy-webapp#1]
afshan@afshan-VirtualBox:~/keras-flask-deploy-webapp$ python3 app.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    model = load_model(MODEL_PATH)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 268, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

I am getting error ValueError: No model found in config file when I pass save.h5 file to FILE_PATH. 

Any one can help??

**Comment by mtobeiyf** [comment]
It seems that you want to loaded the weights as a model. You need to define the model before load the weights and feed them in.
Use `model.save` function to save that model with both the architecture and weights.
See the issue https://github.com/keras-team/keras/issues/6937 for more help.

**Comment by Afshan-anwar** [comment]
When using model.save I am receiving this error message

CODE:

# Define a flask app
app = Flask(__name__)

# Model saved with Keras model.save()
model.save('models/facial_expression_model_weights.h5')
MODEL_PATH = '/home/afshan/emo1_tf_keras/model/facial_expression_model_weights.h5'

ERROR:

afshan@afshan-VirtualBox:~/keras-flask-deploy-webapp$ python3 app.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    model.save('models/facial_expression_model_weights.h5')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2591, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 126, in save_model
    'config': model.get_config()
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 1395, in get_config
    if isinstance(self.layers[0], legacy_layers.Merge):
IndexError: list index out of range

**Comment by Afshan-anwar** [comment]
As I am changing the code, error changes but nothing is resolved. 

Can you please look at this file and edit it to some extent for me. 

from __future__ import division, print_function
# coding=utf-8
import sys
import os
import glob
import re
import numpy as np

# Keras
from keras.applications.imagenet_utils import preprocess_input, decode_predictions
from keras.models import load_model
from keras.preprocessing import image
from keras.models import Sequential

# Define a flask app
app = Flask(__name__)

# Flask utils
from flask import Flask, redirect, url_for, request, render_template
from werkzeug.utils import secure_filename
from gevent.wsgi import WSGIServer

model = Sequential()
def create_model():
   model = Sequential()
   model.add(Dense(64, input_dim=14, init='uniform'))
   model.add(LeakyReLU(alpha=0.3))
   model.add(BatchNormalization(epsilon=1e-06, mode=0, momentum=0.9, weights=None))
   model.add(Dropout(0.5)) 
   model.add(Dense(64, init='uniform'))
   model.add(LeakyReLU(alpha=0.3))
   model.add(BatchNormalization(epsilon=1e-06, mode=0, momentum=0.9, weights=None))
   model.add(Dropout(0.5))
   model.add(Dense(2, init='uniform'))
   model.add(Activation('softmax'))
   return model

def train():
   model = create_model()
   sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
   model.compile(loss='binary_crossentropy', optimizer=sgd)

   checkpointer = ModelCheckpoint(filepath='models/facial_expression_model_weights.h5', verbose=1, save_best_only=True)
   model.fit(X_train, y_train, nb_epoch=20, batch_size=16, show_accuracy=True, validation_split=0.2, verbose=2, callbacks=[checkpointer])

def load_trained_model(weights_path):
   model = create_model()
   model.load_weights(weights_path)

intermediate_layer_model = Model(inputs=model.input, outputs=model.get_layer(layer_name).output)
a = Input(shape=(32,))
b = Dense(32)(a)
model = Model(inputs=a, outputs=b)

model.load_weights('models/facial_expression_model_weights.h5', by_name=True)

# Model saved with Keras model.save()
model.save('models/facial_expression_model_weights.h5')
MODEL_PATH = 'models/facial_expression_model_weights.h5'

# Load your trained model
#model = load_model(MODEL_PATH)
model.load_weights('models/facial_expression_model_weights.h5')
model._make_predict_function()          # Necessary
print('Model loaded. Start serving...')


def model_predict(img_path, model):
    img = image.load_img(img_path, target_size=(224, 224))

    # Preprocessing the image
    x = image.img_to_array(img)
    # x = np.true_divide(x, 255)
    x = np.expand_dims(x, axis=0)

    # Be careful how your trained model deals with the input
    # otherwise, it won't make correct prediction!
    x = preprocess_input(x, mode='caffe')

    preds = model.predict(x)
    return preds

@app.route('/', methods=['GET'])
def index():
    # Main page
    return render_template('index.html')

@app.route('/predict', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        # Get the file from post request
        f = request.files['file']

        # Save the file to ./uploads
        basepath = os.path.dirname(__file__)
        file_path = os.path.join(
            basepath, 'uploads', secure_filename(f.filename))
        f.save(file_path)

        # Make prediction
        preds = model_predict(file_path, model)

        # Process your result for human
        # pred_class = preds.argmax(axis=-1)            # Simple argmax
        pred_class = decode_predictions(preds, top=1)   # ImageNet Decode
        result = str(pred_class[0][0][1])               # Convert to string
        return result
    return None


if __name__ == '__main__':
    # app.run(port=5002, debug=True)

    # Serve the app with gevent
    http_server = WSGIServer(('', 5000), app)
    http_server.serve_forever()

**Comment by mtobeiyf** [comment]
You have defined `create_model()`, which will return a `model` to you. 
The process should be like this
```python
# def load_trained_model(weights_path):
# ...

#Load your trained model
model = create_model()
model.load_weights('models/facial_expression_model_weights.h5')
model._make_predict_function() # Necessary
print('Model loaded. Start serving...')
```

You need to **learn Keras first** and figure out what each line is doing.

Closing this as this is not a issue or bug of this project.

**Comment by Afshan-anwar** [comment]
ok thanks for your help
