### ISSUE TITLE
Implement_for_Object_detection

### ISSUE THREAD

**Issue by Niranjankumar-c** [mtobeiyf/keras-flask-deploy-webapp#13]
Hi,

I want to deploy my object detection using the same approach. First I will upload the original image on click of predict, the model will process and gives me an annotated image. Then i need to upload it the webpage next to the original image.

I have all the required python code. Can you help me how/what changes i need to do in HTML or js file?

**Comment by mtobeiyf** [comment]
It's easy
First, encode the annotated image as base64 format, like this:
```python
annotated_img = u"data:image/png;base64," + 
        base64.b64encode(open('path/to/image', "rb").read()).decode("ascii")
```
Then, put a image tag in [index.html](/templates/index.html), say in line 28 or any line you want
```
<img src="{{ image }}" />
```
This will automatically show the returned base64 image from the code

Change the line in [app.py](https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/master/app.py#L78) to 
```python
return render_template("index.html", image=annotated_img)
```

Optionally, comment some lines under [main.js](https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/master/static/js/main.js#L45)

**Comment by Niranjankumar-c** [comment]
I have modified the upload function as below, I will be getting the predicted image from yoloclass.

`predicted_image = yolo_cls.detect_image(file_path)`

 I haven't saved the predicted image object anywhere, do i need to save it somewhere?. and then pass that path to encode the annotated image?

**Comment by mtobeiyf** [comment]
You can convert the image object to bytes for the [base64.b64encode](https://docs.python.org/3.7/library/base64.html#base64.b64encode) to work. It depends on your output type (ndarray, PIL Image, ...)
I'd suggest you just save the image to a local folder. Then simply read it using the `open()`. In this way, you may encounter much less problems.

**Comment by Niranjankumar-c** [comment]
I have saved the annotated image in the uploads folder and when i try to convert it to the base64 i am getting an error. why?


```
Traceback (most recent call last):
  File "C:\Users\NiranjanKumar\Anaconda3\envs\test\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\NiranjanKumar\Anaconda3\envs\test\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\NiranjanKumar\Anaconda3\envs\test\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\NiranjanKumar\Anaconda3\envs\test\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\NiranjanKumar\Anaconda3\envs\test\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\NiranjanKumar\Anaconda3\envs\test\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 50, in upload
    annotated_img = u"data:image/png;base64," + base64.b64encode(open('uploads/annotated.jpg', "rb").read()).decode("ascii")
NameError: name 'base64' is not defined
```

**Comment by Niranjankumar-c** [comment]
I fixed the above base64 error, missing an import statement. After executing the app.py and uploading the image, on the press of predict button i am getting the following error in the webpage directly not getting any image. 


![image](https://user-images.githubusercontent.com/36450263/54860493-c92e2100-4d40-11e9-93f3-087698f8a499.png)

![image](https://user-images.githubusercontent.com/36450263/54860516-1b6f4200-4d41-11e9-845f-3b4501ef9473.png)
Uploading the app.py in text format[app.txt](https://github.com/mtobeiyf/keras-flask-deploy-webapp/files/2998928/app.txt)

**Comment by mtobeiyf** [comment]
As I said before, you should comment some lines under main.js

**Comment by Niranjankumar-c** [comment]
Can you tell me what lines to comment/modify in main.js. I have no experience in js or html.

On Mar 24, 2019 11:18 AM, Fing <notifications@github.com> wrote:

As I said before, you should comment some lines under main.js

**Comment by mtobeiyf** [comment]
My bad, I made this thing too complicated.
Just make the following changes:

In app.py, line 51 and 52, following your code:
```python
annotated_img = u"data:image/png;base64," + base64.b64encode(open('uploads/annotated.jpg', "rb").read()).decode("ascii")
return annotated_img   # don't do the render_template this time
```

In index.html, line 24, add an tag:
```html
<img id="result-image" src="" />
```

In main.js, line 48, replace the original line with:
```js
$('#result-image').attr("src", data);
```

It should work this time.

**Comment by Niranjankumar-c** [comment]
Did all the changes as you said, this time no error but still the predicted image is not getting displayed.

check these images

![image](https://user-images.githubusercontent.com/36450263/54882046-06e39480-4e7c-11e9-9db3-85c6273eb205.png)

![image](https://user-images.githubusercontent.com/36450263/54882020-e3b8e500-4e7b-11e9-9a97-61ba7d3b88c7.png)

**Comment by mtobeiyf** [comment]
I've tried the above modification myself, it's supposed to work.
The images provided by you does not have useful information for me to see which part is wrong.
Could you please debug a little bit yourself, like `print` the returned image data in app.py, and `console.log(data)` in main.js to display the received the data in the browser, use F12 to inspect the image tag to see if the src is correctly set to the data received by the js ajax call. And then do some modification.
If the `console.log` could show the encoded image data, another possible cause may be the format should set to `data:image/jpeg;` rather than `data:image/png;` for the annotated image.

**Comment by Niranjankumar-c** [comment]
I have changed the data format to `data:image/jpg` then it started to work. Thank you.

But i need to little bit beautification like i want the uploaded image to be little bigger and annotated image also needs to be same size and displayed next to it, rather than the below. Can you help me with the html code?
![image](https://user-images.githubusercontent.com/36450263/55127361-e0508280-5135-11e9-8c16-a2255990bd23.png)

**Comment by Niranjankumar-c** [comment]
One more thing, when i upload a new image i want the old annotated image to be removed. How can i achieve this functionality in js?

In the pic, i uploaded a new car image - old annotated red car image is still visible, i want that to be gone.
![image](https://user-images.githubusercontent.com/36450263/55127548-87351e80-5136-11e9-8053-57e24b0daaf3.png)

**Comment by Niranjankumar-c** [comment]
Can you reopen this issue?

**Comment by mtobeiyf** [comment]
For styling the image, add some rule in the [main.css](https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/master/static/css/main.css)
For removing some element, write some simple js code in [main.js](https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/master/static/js/main.js)

I wrote pretty many comments in the source code to explain how each line works.
**Please read the code and do it yourself.**

**Comment by NiklasDL** [comment]
Hi @mtobeiyf 

I was trying to adapt from your suggestions but I do receive just a string as result (see image below).
Any idea what I'm doing wrong?

![image](https://user-images.githubusercontent.com/26283174/55291939-f2a41800-53e4-11e9-95c4-5f65596493bf.png)

**Comment by mtobeiyf** [comment]
@NiklasDL Follow this https://github.com/mtobeiyf/keras-flask-deploy-webapp/issues/13#issuecomment-475951705
Seems like you forgot to change the javascript code to display the image on the `img` tag.

**Comment by NiklasDL** [comment]
Hm, no, unfortunately not. But the good yet weird news are that the very same code works from my cloud machine at work.

Thanks for the great repository!

**Comment by mtobeiyf** [comment]
Rebooting your computer makes everything work, lol 😂 

BTW, happy April Fools' Day 👻

**Comment by pranavpawar3** [comment]
> My bad, I made this thing too complicated.
> Just make the following changes:
> 
> In app.py, line 51 and 52, follow your code:
> 
> ```python
> annotated_img = u"data:image/png;base64," + base64.b64encode(open('uploads/annotated.jpg', "rb").read()).decode("ascii")
> return annotated_img   # don't do the render_template this time
> ```
> 
> In index.html, line 24, add an image tag:
> 
> ```
> <img id="result-image" src="" />
> ```
> 
> In main.js, line 48, replace the original line with:
> 
> ```js
> $('#result-image').attr("src", data);
> ```
> 
> No need to comment anything.
> It should work this time.

Hey I tried doing this, doesnt work, I am trying to display a saved segmented output image, do I need to change anything else? Woul;d be great if you revert back quickly, am sort of stuck on this!

**Comment by mtobeiyf** [comment]
Check out the previous version as I mentioned in the README: https://github.com/mtobeiyf/keras-flask-deploy-webapp/tree/legacy

**Comment by amyburden** [comment]
I try several times and it doesn't work. I found the main problem is browser may save the cache and do not load the newest code as expected. I try to use the private mode of the browser and find out that works. Remember to open new private windows when testing.
