### ISSUE TITLE
ImportError: Could not import PIL.Image. The use of load_img requires PIL.

### ISSUE THREAD

**Issue by weishengchong** [mtobeiyf/keras-flask-deploy-webapp#20]
Hi,

FYI, after selected image and click predict, no prediction results after waiting for 1 minute, found error below.
  raise ImportError('Could not import PIL.Image. '
ImportError: Could not import PIL.Image. The use of load_img requires PIL.

solution 
apt-get install python-pillow
reference https://github.com/python-pillow/Pillow/issues/3088

my env
ubuntu18.04
python 3.5 <- same error after "apt-get install python-pillow"
python 3.6 <- error solved after "apt-get install python-pillow"

test solution
test with Python 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0] on linuxType "help", "copyright", "credits" or "license" for more information.>>> from PIL import Image as pil_image

**Comment by mtobeiyf** [comment]
You need to directly install `pillow` package using `$ pip install pillow`
