### ISSUE TITLE
Object detection

### ISSUE THREAD

**Issue by abdou31** [mtobeiyf/keras-flask-deploy-webapp#22]
Hello , 
Can you please make a tutorial of object detection problem ??

**Comment by mtobeiyf** [comment]
Please take a look at this issue https://github.com/mtobeiyf/keras-flask-deploy-webapp/issues/13. It might help

**Comment by IdeaKing** [comment]
@mtobeiyf I was able to go through the legacy version and create the object detection version. But I would really like an object detection version for the main (newer) page. Can you help walk me through any needed modifications? I don't know where to start as I have already tried creating an object detection version without anything working.

**Comment by mtobeiyf** [comment]
@IdeaKing 
It's basically similar to #13 
First, you need to modify the prediction result as an image with bounding boxes.
https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/39144f7304c2fa76229e62b4b00f244115f4a8e4/app.py#L57-L58

In the `predict()` function in `app.py`, serialize the output image into a base64 string, replace the result with the base64 image.
https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/39144f7304c2fa76229e62b4b00f244115f4a8e4/app.py#L87

Modify the `displayResult` function in `static/main.js`. Here, you'll get the result from the above `predict()` function. 
https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/39144f7304c2fa76229e62b4b00f244115f4a8e4/static/main.js#L131-L137

All you have to do is to modify the `image-display` using the `displayImage()` function. 
https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/39144f7304c2fa76229e62b4b00f244115f4a8e4/static/main.js#L96

Provide it with the returned base64 image in the `result` field. For example:

```js
function displayResult(data) { 
   hide(loader); 
   displayImage(data.result, "image-display");
 }
```

**Comment by IdeaKing** [comment]
@mtobeiyf Thank you so so much! It works perfectly. However, there's one problem, output box is shaded. What should I change? Here's an example:
![temp](https://user-images.githubusercontent.com/66394854/92145002-8f8e9000-ede5-11ea-8abe-7ab3969a4c45.png)
Btw, I think you should also paste your previous comment in the readme after you close this issue/topic.

**Comment by mtobeiyf** [comment]
@IdeaKing oh, just remove the `loading` class for the `imageDisplay` element at the last step:
```js
function displayResult(data) { 
  hide(loader); 
  displayImage(data.result, "image-display");
  imageDisplay.classList.remove("loading");
}
```

**Comment by IdeaKing** [comment]
@mtobeiyf Great! Thank you for all of the help.

**Comment by cuonghip0908** [comment]
@mtobeiyf by this way, we don't need to edit file index.html, right? i replaced result by annotated_img  in the predict function (app.py) and edit displayResult function in main.js by your tutorials but it doesn't work? can you help me?

**Comment by IdeaKing** [comment]
@counghip0908 This is due to browser cache. Turn on dev tools in your
browser (for Chrome the shortcut is F12) and remove all cache for your
website and then reload. All of @mtobeiyf steps work very well.

**Comment by cuonghip0908** [comment]
oh, i understood problem and solved, it worked very well, many tks :))

Vào Th 3, 15 thg 9, 2020 vào lúc 06:39 Thomas Chia <
notifications@github.com> đã viết:
