### ISSUE TITLE
ValueError: Error when checking input: expected conv2d_1_input to have shape

### ISSUE THREAD

**Issue by bhooshan1996** [mtobeiyf/keras-flask-deploy-webapp#23]
I had loaded my own model as mentioned by you. While my training I had resized images with 28*28. 
I have changed this img size in your app.py also but now I am getting error as mentioned below:

"ValueError: Error when checking input: expected conv2d_1_input to have shape (28, 28, 3) but got array with shape (28, 28, 4)"
Can you please tell me how can I convert 28,28,4 to 28,28,3 so that I could get predictions as per my model ?

**Comment by mtobeiyf** [comment]
You are most likely using a `.PNG` image, which has 4 channels `RGBA`. 
Please convert it to `RGB` with PIL: https://stackoverflow.com/a/43258974

**Comment by bhooshan1996** [comment]
Yes, I solved it by converting to RGB :)

`def model_predict(img, model):

    # pre-process the image for classification
    img = img.convert('RGB')
    img = img.resize((28, 28))
    # Preprocessing the image
    x = image.img_to_array(img)
    #x = np.asarray(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x, mode='tf')
    
    # classify the input image
    (nt, weapon) = model.predict(x)[0]
    return nt, weapon`

Thanks :)

**Comment by mtobeiyf** [comment]
No problem 😄
