### ISSUE TITLE
 a error occurred !

### ISSUE THREAD

**Issue by kavin901020** [mtobeiyf/keras-flask-deploy-webapp#24]
MODEL_PATH = '/home/ljs/keras-flask-deploy-webapp/models/densenet121.h5'
 File "/home/ljs/anaconda3/envs/zk/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 175, in load_model_from_hdf5
    raise ValueError('No model found in config file.')

when I plan to use a downloaded keras model, above problem occurred, please help me.

**Comment by mtobeiyf** [comment]
Try the DenseNet provided by Keras. Check out the example at https://keras.io/api/applications/
