### ISSUE TITLE
Error importing MobileNetV2

### ISSUE THREAD

**Issue by Sumanthnr93** [mtobeiyf/keras-flask-deploy-webapp#26]
May be this is an issue with tensorflow version. Since requirements.txt does not define the tensorflow version, it's installing latest version and latest version needs - 
`from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2`

https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/59f6c9859bc1342bed76ec44536d293641881d1f/app.py#L28

**Comment by mtobeiyf** [comment]
What does the error message look like?

**Comment by mtobeiyf** [comment]
Fixed versions. This should work.

https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/466a7892b760f4f8453f8df990844d5ad7f91389/requirements.txt#L1-L8

**Comment by Sumanthnr93** [comment]
Great, Thanks. This was the error `AttributeError: module 'tensorflow' has no attribute 'get_default_graph'`
I am using tensorflow 2.3.0, for future reference if anyone faces this I can confirm adding `tensorflow.` in front of keras.applications.mobilenet_v2 fixes the issue.

**Comment by mtobeiyf** [comment]
thanks. I'll fix this issue. Since Keras has been integrated into tensorflow 2.0+, I think it's better to remove individual Keras dependency.
