### ISSUE TITLE
Value Error: decode predictions

### ISSUE THREAD

**Issue by Dropcodee** [mtobeiyf/keras-flask-deploy-webapp#29]
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 2)

172.17.0.1 - - [2020-10-05 15:30:02] "POST /predict HTTP/1.1" 500 411 0.227771

Please I need help, once I run the docker build with my model I just get a 500 error them the terminal trows back this error above.

**Comment by mtobeiyf** [comment]
Please check you input. Use `print` to display some intermediate variables.
