### ISSUE TITLE
Problem using another .h5

### ISSUE THREAD

**Issue by paolodavid** [mtobeiyf/keras-flask-deploy-webapp#30]
Hi I tried your project and I liked it ;)

I tried also to change another .h5 file to create only a binary classification (dogs vs cats) but uncommenting the lines of the code to do it and putting my.h5 in the model folder, I have different problems. Can you explain me which should be the features to create a .h5 file to work on it ?
For example I tried to used this .h5 file (https://drive.google.com/open?id=19yICdtSbU_YkQBRxJ2if9KJwUL1oY5xs) from this tutorial (https://deeplizard.com/learn/video/XgzxH6G-ufA) to create only a binary classification.

Can you explain me how to re-edit it to work with this tutorial?

Thanks in advance and let me know.

I really appreciate your project 👍🏻

**Comment by mtobeiyf** [comment]
Basically, you just need to modify these lines in.`app.py`:

https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/39144f7304c2fa76229e62b4b00f244115f4a8e4/app.py#L30-L42

Comment out line 31, and uncomment line 40. Once the model is successfully loaded, you should be good to go.

**Comment by paolodavid** [comment]
Thanks for the answer. I did it but , using this .h5 (https://drive.google.com/open?id=19yICdtSbU_YkQBRxJ2if9KJwUL1oY5xs) file inside the /models folder I have this error

`   pred_class = decode_predictions(preds, top=1)   # ImageNet Decode
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/applications/__init__.py", line 49, in wrapper
    return base_fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/applications/imagenet_utils.py", line 30, in decode_predictions
    return imagenet_utils.decode_predictions(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras_applications/imagenet_utils.py", line 222, in decode_predictions
    'Found array with shape: ' + str(preds.shape))
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 2)
172.17.0.1 - - [2020-10-21 15:58:12] "POST /predict HTTP/1.1" 500 411 0.527850`

Where do you think could be the error?

I'm trying to re-adapt this tutorial (https://deeplizard.com/learn/video/XgzxH6G-ufA) to your model.

**Comment by mtobeiyf** [comment]
Seems like the output decoding should be modified, since you're not using imagenet model, which has 1000-dim output (but yours just has 2 classes). 

Check out these lines. Pick the max, set the result to `"dog"` or `"cat"` accordingly.

https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/39144f7304c2fa76229e62b4b00f244115f4a8e4/app.py#L79-L84

**Comment by paolodavid** [comment]
Thank again. I tried to re-edit in this way:

`        # Make prediction
        preds = model_predict(img, model)

        # Process your result for human
        pred_proba = "{:.3f}".format(np.amax(preds))    # Max probability
        pred_class = decode_predictions(preds, top=1)   # ImageNet Decode

        #result = str(pred_class[0][0][1])               # Convert to string
        #result = result.replace('_', ' ').capitalize()

        #prediction = model.predict(processed_image).tolist()

        result = {
            'pred_class': {
                'dog': pred_class[0][0],
                'cat': pred_class[0][1]
            }
        }`


But same error. Can you re-edit it rapidly please 🙏🏻 ?

**Comment by mtobeiyf** [comment]
The `result` variable is just a string. You need to assign either 'dog' or 'cat' to it, based on your prediction output.

**Comment by paolodavid** [comment]
I tried in this way

```
        result = {

                'dog': pred_class[0][0],
                'cat': pred_class[0][1]

        }
```

but I have this error

```
 File "/usr/local/lib/python3.6/site-packages/keras_applications/imagenet_utils.py", line 222, in decode_predictions
    'Found array with shape: ' + str(preds.shape))
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 2)
```

**Comment by paolodavid** [comment]
I tried now with the code at left of this screen

https://ibb.co/fdX31VK

and I obtain this

https://ibb.co/JvDBMMf

I think I'm near to the solution. 

Can you help me in these last steps?

**Comment by mtobeiyf** [comment]
I told you the `result` variable should be a string, not a json-like dictionary. For example

```
@app.route('/predict', methods=['GET', 'POST'])
def predict():
    if request.method == 'POST':
        # Get the image from post request
        img = base64_to_pil(request.json)

        # Save the image to ./uploads
        # img.save("./uploads/image.png")

        # Make prediction
        preds = model_predict(img, model)

        # determine it's a dog or cat
        # then, assign it to the result, for example
        if preds[0][0] > preds[0][1]:
            result = "dog"
        else:
            result = "cat"

        # Serialize the result, you can add additional fields
        return jsonify(result=result)

    return None

```

**Comment by paolodavid** [comment]
Ok great, now it works. Thank you again ;)
