### ISSUE TITLE
--gpus all

### ISSUE THREAD

**Issue by wubinbai** [mtobeiyf/keras-flask-deploy-webapp#34]
Is there options to run DL with GPU here? I use docker run --rm --gpus all nvidia/cuda nvidia-smi from https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html but this does not seem to work: it does not use GPU at all, instead, it is using CPU and it is very slow.

**Comment by mianasbat** [comment]
I was having issue with using gpus, I did the following and it started working.
First check if nvidia-container-toolkit is installed on the host machine or not by
```
nvidia-container-cli info
```
If it is not installed then run the following commands and try to run your docker again
```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list


sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
sudo systemctl restart docker
```
Reference: https://dev.to/et813/install-docker-and-nvidia-container-m0j

**Comment by mtobeiyf** [comment]
I think to run with GPU, you have to use nvidia-docker.
@mianasbat Thanks for the detailed information 👍

**Comment by mianasbat** [comment]
Just to add after running the above commands to install nvidia-container-toolkit on the host machine. You need to give permission of docker to local users again i.e.
```
sudo chmod 666 /var/run/docker.sock
sudo chgrp docker /lib/systemd/system/docker.socket
sudo chmod g+w /lib/systemd/system/docker.socket
```
