### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by sametdumankaya** [mtobeiyf/keras-flask-deploy-webapp#4]
Hello. Thanks for great repository.

There is an issue when I containerized the Flask application. When I run docker build command, it simply builds and creates an image but when I run the docker image as a container it's stuck in the line which it tries to download default Keras ResNet50 model.

![capture](https://user-images.githubusercontent.com/12208827/42722316-8850e69a-8739-11e8-86b0-af26e20a6a59.png)

and so localhost:5000 is not answering. I have modified the docker file like follows:

**FROM ubuntu:latest
RUN apt-get update -y && apt-get install -y python python-dev python-pip python-virtualenv build-essential && rm -rf /var/lib/apt/lists/*
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]**

**Comment by mtobeiyf** [comment]
Thank you for pointing that out. :+1: 
You can fork and make a PR. 

@xtellurian Take a look at this.

**Comment by xtellurian** [comment]
Interesting - I was using a custom model so I didn't run into this problem. However I did see another person run the sample model downloaded similar to yours.

Localhost:5000 won't respond till the model finishes downloading

**Comment by sametdumankaya** [comment]
Yes you're right. Server responses after finishing download but I can't understand when it finishes. When I built and run project locally (not on Docker), it says "Check 127.0.0.1:5000". I think dockerized server should also log to console after downloading the model.

**Comment by physhik** [comment]
I had the same issue, 

First of all, check "python app.py" works at your local. If yes, 


I modified the end of Dockerfile a bit 

```python
RUN pip install -r requirements.txt

EXPOSE 5000
CMD [ "python" , "app.py"]
```

Build your docker image again, and run it 

$ docker run -d -p 5000:5000 keras_flask

open
0.0.0.0:5000

**Comment by physhik** [comment]
The Docker is updated and won't make a problem.

**Comment by mtobeiyf** [comment]
@physhik Thanks. Issue closed.
