### ISSUE TITLE
expected conv2d_1

### ISSUE THREAD

**Issue by amirasyraf** [mtobeiyf/keras-flask-deploy-webapp#7]
I'm getting 

`ValueError: Error when checking input: expected conv2d_1_input to have shape (150, 150, 3) but got array with shape (224, 224, 3)`

after clicking 'Predict' using my own model trained with Keras. 

Attached is the model.h5 if anyone is interested in trying it out.

Tensorflow: 1.12.0
Keras: 2.2.4
Python: 3.5.2

[model.zip](https://github.com/mtobeiyf/keras-flask-deploy-webapp/files/2600354/model.zip)

**Comment by mtobeiyf** [comment]
Seems that you need to resize the input image to `(150, 150, 3)`, so that it will fit the input layer of your own trained model.

**Comment by amirasyraf** [comment]
Thanks.

But unfortunately now I'm getting:

`ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 1)`

**Comment by mtobeiyf** [comment]
You need to **modify the code** based on your model structure. 
You could print it using `model.summary()`
For other reference, go to the official document https://keras.io/
